baseurl = "/"
title = "My Personal Portfolio"
author = "Hayden Drummond"
canonifyurls = true
paginate = 3
theme = "aether-master"

[params]
brand = "Hayden Drummond 13239431"
description = "My Personal Portfolio"
bgimg = "img/pattern.jpg"
